### ISSUE TITLE
Uncaught Error: Singleton client API not yet initialized, cannot call addParameters

### ISSUE THREAD

**Issue by husayt** [eirslett/storybook-builder-vite#50]
I have managed to get storybook running with start-storybook. I have also now managed to get the build compete.
But when I open the generated SB page I get the following error:

```
iframe.778fe525.js:33 Uncaught Error: Singleton client API not yet initialized, cannot call addParameters
    at addParameters (iframe.778fe525.js:33)
    at iframe.778fe525.js:90
    at Array.forEach (<anonymous>)
    at iframe.778fe525.js:90
    at Array.forEach (<anonymous>)
    at iframe.778fe525.js:90
```

Has anyone seen something similar perhaps?

I am using vue3  on windows.

**Comment by husayt** [comment]
This seems to be related to https://github.com/storybookjs/storybook/issues/15210

**Comment by husayt** [comment]
Now it only works if I disable all plugins including essential pugins., which defies the purpose. Maybe this can help to identify the issue.

**Comment by martinsuba** [comment]
I'm getting the same error after upgrading from 6.1.11. to 6.3.2. I've also tried upgrading to 6.4.0-alpha.12 (with webpack 5) and the result is same, except now I'm also getting this in console:
`99% done plugins webpack-hot-middlewarewebpack built preview dbb930f7764ba3c321a1 in 1409ms`
Seems like the built is stuck somehow, and there's an infinite loader on the storybook page.

**Comment by Enteleform** [comment]
I'm getting a similar error with Storybook `6.3.6` & Vite `2.4.4`, for both `start-storybook` and `build-storybook`.

Rolling Vite back to `2.4.2` seems to work for `start-storybook`, but not `build-storybook`.

Below are the relevant dependencies. All of the dependencies in my project, including the ones listed below, are the most recent versions available as of today. I am using addons, but the issues still occur if they're disabled, so I omitted them from the list.

-----

**package.json/dependencies**
```json
"@storybook/svelte":             "6.3.6",
"@storybook/addon-svelte-csf":   "1.1.0",
"storybook-builder-vite":        "0.0.12",

"svelte":                        "3.41.0",
"svelte-hmr":                    "0.14.7",
"svelte-preprocess":             "4.7.4",
"@tsconfig/svelte":              "2.0.1",

"vite":                          "2.4.4",
"vite-tsconfig-paths":           "3.3.13",
"@sveltejs/vite-plugin-svelte":  "1.0.0-next.15",
```

-----

**console.error**
```log
client_api.js:55 Uncaught Error: Singleton client API not yet initialized, cannot call addParameters
    at addParameters (client_api.js:55)
    at vite-app.js:31
    at Array.forEach (<anonymous>)
    at vite-app.js:17
    at Array.forEach (<anonymous>)
    at vite-app.js:16
```

**Comment by husayt** [comment]
I finally found a solution to this [here](https://github.com/storybookjs/storybook/issues/10887#issuecomment-901109891_)
I will just copy the correct answer, as it solved this for once: 

> The solution for vite builder — force dedupe (see https://github.com/eirslett/storybook-builder-vite#customize-vite-config):
> ```
> async viteFinal(config, {configType}) {
>     config.resolve.dedupe = ["@storybook/client-api"]
>     return config
> },
> ```
> 

Thanks @develar

**Comment by mariusheine** [comment]
@husayt Awesome and thx! This fixed it for us as well 😃 

Now we only need to wait for the root problem to be solved. I am wondering if this is a vite builder specific problem or if the root problems lies in the storybook core as others have the same problem with other builders... 🤔

**Comment by shilman** [comment]
For those of you for whom this dedupe solution works 👆, I'm wondering why you have multiple copies of `@storybook/client-api` installed? Perhaps you need to make sure your storybook-related packages are on the same version?

This should help:

```
npx sb info
```

**Comment by Enteleform** [comment]
@shilman
`npx sb info` didn't seem to provide much useful info:

```yaml
System:
  OS: Windows 10 10.0.19042
  CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Binaries:
  Node: 16.4.2 - C:\_\Dev\NodeJS\1~6\node.EXE
  Yarn: 1.22.10 - C:\_\Dev\NodeJS\16\yarn.CMD
  npm: 7.18.1 - C:\_\Dev\NodeJS\16\npm.CMD
Browsers:
  Chrome: 93.0.4577.63
  Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.38)
npmPackages:
  @storybook/addon-actions: 6.3.8 => 6.3.8
```

Might be because I'm using a Yarn workspace?

&nbsp;
Here's a full list of my Svelte/Vite/Storybook related dependencies. I just updated them all to `latest` as of today (*was stuck on a few older versions before the fix*), but I just confirmed that the issue does still occur \***without**\* the fix, even with the latest dependencies. Seems to be working fine once deduped though 👍.

```json
{
  "svelte":                        "3.42.5",
  "@tsconfig/svelte":              "2.0.1",
  "svelte-hmr":                    "0.14.7",
  "svelte-preprocess":             "4.9.4",

  "vite":                          "2.5.7",
  "@sveltejs/vite-plugin-svelte":  "1.0.0-next.23",
  "vite-plugin-optimize-persist":  "0.0.5",
  "vite-plugin-package-config":    "0.0.3",
  "vite-tsconfig-paths":           "3.3.14",
  
  "@storybook/svelte":             "6.3.8",
  "@storybook/addon-svelte-csf":   "1.1.0",
  "storybook-builder-vite":        "0.0.12",

  "@storybook/addon-actions":      "6.3.8",
  "@storybook/addon-controls":     "6.3.8",
  "@storybook/addon-docs":         "6.3.8",
  "@storybook/addon-events":       "6.2.9",
  "@storybook/addon-links":        "6.3.8",
  "@storybook/addon-measure":      "6.4.0-alpha.27",
  "@storybook/addon-outline":      "6.4.0-alpha.27",
  "@storybook/addon-postcss":      "2.0.0",
  "@storybook/addon-storysource":  "6.3.8",
  "@storybook/addon-toolbars":     "6.3.8",
  "@storybook/addon-viewport":     "6.3.8",
  "@storybook/theming":            "6.3.8",

  "storybook-addon-paddings":      "4.2.1",
  "storybook-addon-pseudo-states": "1.0.0",
  "storybook-addon-themes":        "6.1.0",
  "storybook-dark-mode":           "1.0.8",
  "storybook-facelift":            "6.9.0",
  "storybook-stylesheet-toggle":   "0.1.3"
}
```

**Comment by shilman** [comment]
If you downgrade addon-measure and addon-outline to 6.3.8, and remove addon-events, does that fix it without the dedupe?

**Comment by Enteleform** [comment]
@shilman 
> If you downgrade addon-measure and addon-outline to 6.3.8, and remove addon-events, does that fix it without the dedupe?

So neither of those seems to actually have a `6.3.8` version. However, I had done a bit of debugging when I first ran into the issue, and just tried the same approach again with the same results. Removing all non-essential addons (*both official & 3rd party*) still results in the error.

Here is the reduced dependency list:
```json
{
  "svelte":                        "3.42.5",
  "@tsconfig/svelte":              "2.0.1",
  "svelte-hmr":                    "0.14.7",
  "svelte-preprocess":             "4.9.4",

  "vite":                          "2.5.7",
  "@sveltejs/vite-plugin-svelte":  "1.0.0-next.23",
  "vite-plugin-optimize-persist":  "0.0.5",
  "vite-plugin-package-config":    "0.0.3",
  "vite-tsconfig-paths":           "3.3.14",
  
  "@storybook/svelte":             "6.3.8",
  "@storybook/addon-svelte-csf":   "1.1.0",
  "storybook-builder-vite":        "0.0.12",
}
```

**Comment by husayt** [comment]
@shilman it might also be related to #55 as I use pnpm and have to enable hoisting. That might be causing ambiguity with peer dependencies which requires dedupe to work.

**Comment by fdc-viktor-luft** [comment]
I can confirm that I ran into the same problem using `pnpm` without shamefully hoisting 😞

**Comment by 0x009922** [comment]
I ran into it too, even with `pnpm i --shamefully-hoist`.

**Comment by joshwooding** [comment]
Re-opening this since we reverted the fix. Something interesting I found is that this error does not occur when storyStoreV7 is enabled.

**Comment by spacedawwwg** [comment]
I'm hitting this issue to using `@storybook/vue3` + `@storybook/addon-essentials`

```YAML
Environment Info:

  System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 3.1.1 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.3 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Edge: 97.0.1072.69
    Firefox: 96.0.2
    Safari: 15.2
  npmPackages:
    @storybook/addon-essentials: next => 6.5.0-alpha.23 
    @storybook/addon-links: next => 6.5.0-alpha.23 
    @storybook/vue3: next => 6.5.0-alpha.23 
 ```
 
 Using
 
 ```JS
module.exports = {
  features: {
    storyStoreV7: true,
  },
}
 ```
 
 to get by for now
